import { StyleSheet, Platform } from "react-native";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#ffffff" },
  webview: { flex: 1, backgroundColor: "#ffffff" },
  loaderOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 10,
    backgroundColor: "#ffffff",
    justifyContent: "center",
    alignItems: "center",
  },
  offlineContainer: {
    flex: 1,
    backgroundColor: "#ffffff",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 32,
  },
  offlineBrand: {
    position: "absolute",
    top: 24,
    fontSize: 14,
    fontWeight: "700",
    letterSpacing: 4,
    color: "#111111",
  },
  offlineTitle: {
    fontSize: 20,
    fontWeight: "700",
    letterSpacing: 1,
    marginBottom: 10,
    color: "#111111",
  },
  offlineText: {
    fontSize: 14,
    color: "#6b6b6b",
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 28,
  },
  retryButton: {
    backgroundColor: "#111111",
    paddingVertical: 14,
    paddingHorizontal: 36,
  },
  retryButtonText: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 2,
  },
  webContainer: {
    flex: 1,
    backgroundColor: "#0f172a",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  webContent: {
    maxWidth: 900,
    width: "100%",
    backgroundColor: "#1e293b",
    borderRadius: 24,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#334155",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.4,
    shadowRadius: 16,
  },
  instructionsPanel: {
    flex: 1,
    padding: 40,
    justifyContent: "center",
  },
  webBrand: {
    fontSize: 24,
    fontWeight: "800",
    letterSpacing: 4,
    color: "#38bdf8",
    marginBottom: 8,
  },
  webTitle: {
    fontSize: 28,
    fontWeight: "700",
    color: "#ffffff",
  },
  webSubTitle: {
    fontSize: 14,
    color: "#94a3b8",
    marginBottom: 24,
  },
  infoCard: {
    backgroundColor: "rgba(56, 189, 248, 0.08)",
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(56, 189, 248, 0.2)",
    marginBottom: 24,
  },
  infoTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#38bdf8",
    marginBottom: 6,
  },
  infoText: {
    fontSize: 13,
    color: "#cbd5e1",
    lineHeight: 18,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#f8fafc",
    marginBottom: 16,
  },
  stepRow: {
    flexDirection: "row",
    marginBottom: 16,
    alignItems: "flex-start",
  },
  stepNumber: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#38bdf8",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
    marginTop: 2,
  },
  stepNumberText: {
    fontSize: 12,
    fontWeight: "800",
    color: "#0f172a",
  },
  stepContent: {
    flex: 1,
  },
  stepTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: "#f1f5f9",
  },
  stepDesc: {
    fontSize: 12,
    color: "#94a3b8",
    marginTop: 2,
  },
  codeText: {
    fontFamily: Platform.OS === "ios" ? "Courier" : "monospace",
    backgroundColor: "#0f172a",
    color: "#38bdf8",
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    fontSize: 12,
  },
  boldText: {
    fontWeight: "700",
    color: "#ffffff",
  },
  phoneFrameContainer: {
    padding: 40,
    backgroundColor: "#0f172a",
    justifyContent: "center",
    alignItems: "center",
  },
  phoneFrame: {
    width: 280,
    height: 560,
    borderRadius: 40,
    backgroundColor: "#000000",
    padding: 10,
    borderWidth: 4,
    borderColor: "#475569",
  },
  phoneDynamicIsland: {
    width: 90,
    height: 20,
    borderRadius: 10,
    backgroundColor: "#000000",
    position: "absolute",
    top: 15,
    alignSelf: "center",
    zIndex: 20,
  },
  phoneScreen: {
    flex: 1,
    backgroundColor: "#ffffff",
    borderRadius: 32,
    overflow: "hidden",
  },
  phoneStatusBar: {
    height: 35,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    backgroundColor: "#ffffff",
  },
  statusTime: {
    fontSize: 12,
    fontWeight: "600",
    color: "#000000",
  },
  statusIcons: {
    flexDirection: "row",
  },
  statusIcon: {
    fontSize: 10,
    marginLeft: 4,
  },
  addressBar: {
    height: 28,
    backgroundColor: "#f1f5f9",
    borderRadius: 8,
    marginHorizontal: 12,
    marginBottom: 6,
    justifyContent: "center",
    alignItems: "center",
  },
  addressText: {
    fontSize: 10,
    color: "#64748b",
  },
  mockAppContent: {
    flex: 1,
    backgroundColor: "#ffffff",
    padding: 12,
  },
  mockAppBrand: {
    fontSize: 18,
    fontWeight: "800",
    letterSpacing: 3,
    color: "#0f172a",
    textAlign: "center",
    marginTop: 4,
  },
  mockNav: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#f1f5f9",
    paddingBottom: 6,
  },
  mockNavItemActive: {
    fontSize: 11,
    fontWeight: "700",
    color: "#0f172a",
    borderBottomWidth: 2,
    borderBottomColor: "#0f172a",
    paddingBottom: 2,
  },
  mockNavItem: {
    fontSize: 11,
    color: "#64748b",
  },
  mockHeroBanner: {
    height: 80,
    backgroundColor: "#1e293b",
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
  },
  mockHeroTitle: {
    fontSize: 16,
    fontWeight: "900",
    color: "#ffffff",
    letterSpacing: 2,
  },
  mockHeroSub: {
    fontSize: 9,
    color: "#94a3b8",
    marginTop: 2,
  },
  mockWarningCard: {
    backgroundColor: "#f8fafc",
    borderRadius: 8,
    padding: 10,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    marginBottom: 10,
  },
  mockWarningTitle: {
    fontSize: 11,
    fontWeight: "700",
    color: "#0f172a",
    textAlign: "center",
    marginBottom: 4,
  },
  mockWarningText: {
    fontSize: 9,
    color: "#475569",
    textAlign: "center",
    lineHeight: 12,
  },
  mockWarningTextSmall: {
    fontSize: 8,
    color: "#94a3b8",
    textAlign: "center",
    marginTop: 4,
    lineHeight: 11,
  },
  mockProductsGrid: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  mockProduct: {
    width: "48%",
  },
  mockProductImage: {
    height: 70,
    backgroundColor: "#f1f5f9",
    borderRadius: 6,
    marginBottom: 4,
  },
  mockProductImage2: {
    height: 70,
    backgroundColor: "#e2e8f0",
    borderRadius: 6,
    marginBottom: 4,
  },
  mockProductTitle: {
    fontSize: 9,
    fontWeight: "600",
    color: "#334155",
  },
  mockProductPrice: {
    fontSize: 8,
    color: "#64748b",
    marginTop: 1,
  },
});